version: '3.1'

services:

  sqldev:
    container_name: sqldev
    image: mysql/mysql-server:5.7
    command: --default-authentication-plugin=mysql_native_password --user=root
    restart: always
    environment:
        MYSQL_ROOT_HOST: '%'
        MYSQL_ROOT_PASSWORD: 123456789
        MYSQL_USER: webuser
        MYSQL_PASSWORD: 123456789
        MYSQL_DATABASE: 'db'
    ports:
      - 3306:3306
